/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.Assert.assertNotNull;

import org.junit.Test;

public class HelloTest {
  @Test
  public void appHasAGreeting() {
    Hello actual = new Hello();
    assertNotNull("app should have a greeting", actual.sayHello("test"));
  }
}
